### PR TITLE
Proposal for Hidden Client ID Randomizing

### PR DESCRIPTION
**Pull request by crackulator**

### CODE REVIEW

**Comment by emveepee** [comment]
This PR should be closed I don't want to see all that noise from the last PR.   Make a post on the Kodi forum to confirm that multi-session linux is supported from the same user and that it doesn't impact the database, logging collision, the user profile, json-rpc etc and if you get Kodi support I will support this.

However I do not want to see any change or documentation in master settings.xml it need to be truly hidden.  The change should also be in the how the client value is returned from settings function not when we are building the URL, in case this is needed in other situations.

**Comment by crackulator** [comment]
That's pretty much what I expected. I'll pass.

**Comment by emveepee** [comment]
It seems you don't think Kodi will support you so I will close this PR.

**Comment by crackulator** [comment]
I talked to the Kodi group about it when I first started the multi-kodis project. Their view was "use at your own risk". It's a rare use-case, not really something they would either support nor prevent. I've been using it quite successfully at my own risk for about 5 years.

**Comment by crackulator** [comment]
Anyway, no worries. It's my own little project, I don't think it was unreasonable to ask to add a hook to make it easier for me, but also not unreasonable for you to decline.

**Comment by emveepee** [comment]
You had not mentioned the multi-kodi project so I did read your git page and like to support developers of small fun projects.   A caveat would be anytime you tell users about this and suggest NextPVR you will need to also tell them it is for personal non-commercial purposes.  

It has the added bonus of creating the hidden setting for you and I get to mask the MAC

How does this work for you?

        self.XNEWA_CLIENT = addon.getSetting("client")
        if  self.XNEWA_CLIENT ==  '':
            import hashlib
            h = hashlib.md5()
            h.update(self.XNEWA_MAC)
            self.XNEWA_CLIENT = h.hexdigest()
            addon.setSetting("client",self.XNEWA_CLIENT)
        elif  self.XNEWA_CLIENT ==  'multi-kodis':
            import random
            self.XNEWA_CLIENT = str(int(round(random.random()*1000)))
        
XNEWA_CLIENT will be used for the client parameter when required not XNEWA_MAC

**Comment by crackulator** [comment]
That would be excellent. I noticed some issues in the emailed version of the code but it looks like you noticed too and fixed it up.

Why do you want to mask the MAC? I thought that a pretty good verification number.

Is it, somewhere else, going to prepend a "KNEW5" or somesuch, like it did previously?

The case of multiple userdata folders, using custom client ID's, is definitely better than random, and I might go there someday, especially if I pick up more users. But it will take significant implementation effort in my script which I don't have much motive to do right now.

**Comment by emveepee** [comment]
I think the client string looks ugly, I guess I am used to guids.   I am thinking of removing KNEW5 I haven't decided, I though it might offer sub somethings to help optimize knewc playback but it is not something he has shown interest in.

You shouldn't have to change your script just create multiple profiles and tell Kodi not to autologon

I will try and upload a branch with this change soon with my changes for your new buttons and some logic fixes.  I think I have got it the way I hoped (new buttons act like a traditional skin, EPG uses the harder logic)

**Pull request closed without merging**
